### PR TITLE
aqua導入

### PR DESCRIPTION
**Pull request by Taiki130**
- resolves https://github.com/chaos-tech/training-note/issues/12

### CODE REVIEW

**Comment by Taiki130** [comment]
```shell
brew install aquaproj/aqua/aqua
aqua install 
```

**Comment by Taiki130** [comment]
@kagunyan25 aqua入れたぞ！

**Review by nysdin — APPROVED** [review]
I think this is nice pr!
Do you have plan to setup automation?

**Review by kagunyan25 — APPROVED** [review]
ぐもにんぐ！

**Comment by Taiki130** [comment]
> I think this is nice pr!
> 
> Do you have plan to setup automation?
> 
> 

@nysdin なにか、文句か！

**Pull request merged**
